version: '3'
services:
  costs-backend:
    build:
      context: ./cost-backend/src/.
    ports:
      - "8000:8000"
  costs-frontend:
    build:
      context: ./cost-frontend/my-finances/.
    ports:
      - "8080:80"

