# Generated by Django 4.2.4 on 2023-08-27 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tatransactionlog',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='tacategory',
            name='FCLASTMODIFIED',
        ),
        migrations.RemoveField(
            model_name='tacategory',
            name='FDUPDATE',
        ),
        migrations.RemoveField(
            model_name='tacategory',
            name='FIIDUSER',
        ),
        migrations.DeleteModel(
            name='TATransaction',
        ),
        migrations.DeleteModel(
            name='TATransactionLog',
        ),
    ]
